# Generated by Django 3.1.3 on 2020-11-24 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memo_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memo',
            old_name='update_datatime',
            new_name='update_datetime',
        ),
    ]
